export const cakes = [
  {
    id: 'cake1',
    type: 'cake',
    price: '35$',
    name: 'Rose Red Velvet Cake',
    img: 'pictures/cake1.jpg',
    description: 'The fluffy top and the graceful cream create a fabulous cake',
    nutrition: {
      fattyCalories: '80.15g',
      saturatedFatAcids: '10.65g',
      carbohydrates: '1.74g',
      sugars: '1.88g',
      proteins: '2.43g',
      salts: '0.22g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs'],
  },
  {
    id: 'cake2',
    type: 'cake',
    price: '45$',
    name: 'Praline Choco',
    img: 'pictures/cake2.jpg',
    description:
      'Praline Choco Cake is a delicious mix of crunchy and fine textures and dense flavors',
    nutrition: {
      fattyCalories: '32.53g',
      saturatedFatAcids: '15.48g',
      carbohydrates: '13.12g',
      sugars: '21.67g',
      proteins: '4.76g',
      salts: '0.14g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs', 'Soy'],
  },
  {
    id: 'cake3',
    type: 'cake',
    price: '40$',
    name: 'Berry Choco',
    img: 'pictures/cake3.jpg',
    description:
      'The Berry Choco cake comes with aromatic but perfectly balanced surprises',
    nutrition: {
      fattyCalories: '58.88g',
      saturatedFatAcids: '11.91g',
      carbohydrates: '8.72g',
      sugars: '13.93g',
      proteins: '2.77g',
      salts: '0.18g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs'],
  },
  {
    id: 'cake4',
    type: 'cake',
    price: '40$',
    name: 'Cherry Vanilla',
    img: 'pictures/cake4.jpg',
    description:
      'Cherry Vanilla is a classic cake, a perfect combination between the delicate aroma of vanilla and the sweet-sour taste of cherries',
    nutrition: {
      fattyCalories: '10.92g',
      saturatedFatAcids: '12.43g',
      carbohydrates: '27.92g',
      sugars: '15.05g',
      proteins: '4.15g',
      salts: '0.78g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs'],
  },
  {
    id: 'cake5',
    type: 'cake',
    price: '40$',
    name: 'Cherry Choco',
    img: 'pictures/cake5.jpg',
    description:
      'A tasty chocolate treat in which cherries come to balance the strong taste and give it a refresh',
    nutrition: {
      fattyCalories: '45.68g',
      saturatedFatAcids: '10.84g',
      carbohydrates: '35g',
      sugars: '30.31g',
      proteins: '3.08g',
      salts: '0.64g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs', 'Soy'],
  },
  {
    id: 'cake6',
    type: 'cake',
    price: '40$',
    name: 'Black Orange',
    img: 'pictures/cake6.jpg',
    description:
      'The Black Orange cake is the embodiment of perfection. Dark chocolate blends wonderfully with the aroma of juicy and tasty oranges',
    nutrition: {
      fattyCalories: '23.12g',
      saturatedFatAcids: '11.44g',
      carbohydrates: '16g',
      sugars: '21.33g',
      proteins: '4.93g',
      salts: '0.12g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs', 'Soy'],
  },
];

export const cookies = [
  {
    id: 'cookie1',
    type: 'cookie',
    price: '4$',
    name: 'Minidrip',
    img: 'pictures/cookie1.jpg',
    description:
      'Cake with cocoa top, Belgian white chocolate mousse with mixed berries',
    nutrition: {
      fattyCalories: '15.96g',
      saturatedFatAcids: '8.22g',
      carbohydrates: '28.63g',
      sugars: '22.41g',
      proteins: '5.37g',
      salts: '0.14g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'cookie2',
    type: 'cookie',
    price: '3$',
    name: 'Ispahan',
    img: 'pictures/cookie2.jpg',
    description:
      'Macarons with rose cream, white chocolate ganache, lychee and raspberry',
    nutrition: {
      fattyCalories: '27.72g',
      saturatedFatAcids: '19.82g',
      carbohydrates: '22.51g',
      sugars: '20.73g',
      proteins: '3.87g',
      salts: '0.19g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'cookie3',
    type: 'cookie',
    price: '3$',
    name: 'Amandine',
    img: 'pictures/cookie3.jpg',
    description: 'Cocoa cake, gold chocolate syrup, rum and cocoa cream',
    nutrition: {
      fattyCalories: '23.58g',
      saturatedFatAcids: '15.82g',
      carbohydrates: '36.28g',
      sugars: '31.09g',
      proteins: '4.63g',
      salts: '0.16g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'cookie4',
    type: 'cookie',
    price: '2.80$',
    name: 'Pistachio tart',
    img: 'pictures/cookie4.jpg',
    description:
      'Tart with pistachio cream, ganache and crunchy pistachio praline',
    nutrition: {
      fattyCalories: '27.72g',
      saturatedFatAcids: '19.82g',
      carbohydrates: '22.51g',
      sugars: '20.73g',
      proteins: '3.87g',
      salts: '0.19g',
    },
    allergens: [
      'Eggs',
      'Wheat Flour',
      'Milk and derived products',
      'Pistachio',
    ],
  },
  {
    id: 'cookie5',
    type: 'cookie',
    price: '2.80$',
    name: 'Pavlova',
    img: 'pictures/cookie5.jpg',
    description:
      'Meringue with mascarpone cream, strawberry jelly and red fruits',
    nutrition: {
      fattyCalories: '9.98g',
      saturatedFatAcids: '2.13g',
      carbohydrates: '28.48g',
      sugars: '19.06g',
      proteins: '4.28g',
      salts: '0.10g',
    },
    allergens: ['Eggs', 'Milk and derived products'],
  },
  {
    id: 'cookie6',
    type: 'cookie',
    price: '4$',
    name: 'Melia',
    img: 'pictures/cookie6.jpg',
    description:
      'Almond crust with a crunchy layer of feuilletine and chocolate, passion fruit mousse and cremeaux and orange confit insert',
    nutrition: {
      fattyCalories: '17.21g',
      saturatedFatAcids: '8.76g',
      carbohydrates: '32.25g',
      sugars: '24.37g',
      proteins: '5.21g',
      salts: '0.17g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products', 'Almond'],
  },
];

export const macarons = [
  {
    id: 'macaron1',
    type: 'macaron',
    price: '1$',
    name: 'Vanilla macaron',
    img: 'pictures/macaron1.jpg',
    description: 'Macarons with vanilla cream',
    nutrition: {
      fattyCalories: '20.71g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '46.76g',
      sugars: '25.41g',
      proteins: '6.47g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron2',
    type: 'macaron',
    price: '1$',
    name: 'Chocolate macaron',
    img: 'pictures/macaron2.jpg',
    description: 'Macarons with chocolate cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron3',
    type: 'macaron',
    price: '1$',
    name: 'Macaron gianduja',
    img: 'pictures/macaron3.jpg',
    description: 'Macarons with gianduja cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: [
      'Eggs',
      'Milk and derived products',
      'Almond',
      'Forest Hazelnuts',
    ],
  },
  {
    id: 'macaron4',
    type: 'macaron',
    price: '1$',
    name: 'Caramel macaron',
    img: 'pictures/macaron4.jpg',
    description: 'Macarons with caramel cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron5',
    type: 'macaron',
    price: '1$',
    name: 'Macaron with chocolate cream and bananas',
    img: 'pictures/macaron5.jpg',
    description: 'Macarons with banana cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron6',
    type: 'macaron',
    price: '1$',
    name: 'Coconut macaron with raspberry',
    img: 'pictures/macaron6.jpg',
    description: 'Macarons with coconut cream and raspberry confit',
    nutrition: {
      fattyCalories: '20.71g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '46.76g',
      sugars: '25.41g',
      proteins: '6.47g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
];

export const eclairs = [
  {
    id: 'eclair1',
    type: 'eclair',
    price: '2.50$',
    name: 'Raspberry Blush Eclair',
    img: 'pictures/eclair1.jpg',
    description: 'Eclair with raspberry cream',
    nutrition: {
      fattyCalories: '19.84g',
      saturatedFatAcids: '12.15g',
      carbohydrates: '20.57g',
      sugars: '14g',
      proteins: '6.34g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair2',
    type: 'eclair',
    price: '2.50$',
    name: 'Vanilla Cream',
    img: 'pictures/eclair2.jpg',
    description: 'Eclair with vanilla cream',
    nutrition: {
      fattyCalories: '22.04g',
      saturatedFatAcids: '11.10g',
      carbohydrates: '16.63g',
      sugars: '10.22g',
      proteins: '5.68g',
      salts: '0.22g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair3',
    type: 'eclair',
    price: '2.50$',
    name: 'Chocolate Mood',
    img: 'pictures/eclair3.jpg',
    description: 'Eclair with chocolate cream',
    nutrition: {
      fattyCalories: '22.84g',
      saturatedFatAcids: '13.54g',
      carbohydrates: '17.10g',
      sugars: '14.92g',
      proteins: '5.37g',
      salts: '0.18g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair4',
    type: 'eclair',
    price: '2.50$',
    name: 'Mango Wish',
    img: 'pictures/eclair4.jpg',
    description: 'Eclair with mango cream',
    nutrition: {
      fattyCalories: '17.67g',
      saturatedFatAcids: '10.74g',
      carbohydrates: '22.46g',
      sugars: '12.75g',
      proteins: '5.74g',
      salts: '0.21g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair5',
    type: 'eclair',
    price: '2.50$',
    name: 'Salty Caramel',
    img: 'pictures/eclair5.jpg',
    description: 'Eclair with salted caramel cream',
    nutrition: {
      fattyCalories: '28.59g',
      saturatedFatAcids: '16.69g',
      carbohydrates: '21.71g',
      sugars: '16.13g',
      proteins: '4.38g',
      salts: '0.50g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair6',
    type: 'eclair',
    price: '2.50$',
    name: 'Coffee Cream',
    img: 'pictures/eclair6.jpg',
    description: 'Eclair with coffee cream',
    nutrition: {
      fattyCalories: '18.65g',
      saturatedFatAcids: '8.73g',
      carbohydrates: '16.96g',
      sugars: '9.14g',
      proteins: '4.82g',
      salts: '0.19g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair7',
    type: 'eclair',
    price: '2.50$',
    name: 'Caramel Cream',
    img: 'pictures/eclair7.jpg',
    description: 'Eclair with sweet caramel cream and smooth milk chocolate',
    nutrition: {
      fattyCalories: '25.18g',
      saturatedFatAcids: '15.15g',
      carbohydrates: '33.16g',
      sugars: '25.50g',
      proteins: '5.76g',
      salts: '0.28g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair8',
    type: 'eclair',
    price: '2.50$',
    name: 'Coconut Dream',
    img: 'pictures/eclair8.jpg',
    description: 'Eclair with coconut cream',
    nutrition: {
      fattyCalories: '22.21g',
      saturatedFatAcids: '11.61g',
      carbohydrates: '30.28g',
      sugars: '21.22g',
      proteins: '5.84g',
      salts: '0.23g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
];

export const pastryGoods = [
  {
    id: 'pastryGood1',
    type: 'pastryGood',
    price: '1$',
    name: 'Croissant',
    img: 'pictures/pastryGood1.jpg',
    description:
      'Every bite is a refined experience because our croissant is generous.',
    nutrition: {
      fattyCalories: '21g',
      saturatedFatAcids: '12g',
      carbohydrates: '46g',
      sugars: '11g',
      proteins: '8g',
      salts: '0.20g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
  {
    id: 'pastryGood2',
    type: 'pastryGood',
    price: '2$',
    name: 'Praline Croissant',
    img: 'pictures/pastryGood2.jpg',
    description:
      'Every bite is an explosion of taste thanks to our hazelnut cream, made from fresh and genuine hazelnuts',
    nutrition: {
      fattyCalories: '17.92g',
      saturatedFatAcids: '10.08g',
      carbohydrates: '8.77g',
      sugars: '16g',
      proteins: '2.32g',
      salts: '0.04g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood3',
    type: 'pastryGood',
    price: '2$',
    name: 'Salted Caramel Vanilla Croissant',
    img: 'pictures/pastryGood3.jpg',
    description:
      'Every bite is a refined experience, as our croissant is generously filled with a delicate and rich vanilla cream and salted caramel insert',
    nutrition: {
      fattyCalories: '17.92g',
      saturatedFatAcids: '10.08g',
      carbohydrates: '8.77g',
      sugars: '16g',
      proteins: '2.32g',
      salts: '0.04g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood4',
    type: 'pastryGood',
    price: '2$',
    name: 'Raspberry Vanilla Croissant',
    img: 'pictures/pastryGood4.jpg',
    description:
      'Every bite is a refined experience, as our croissant is generously filled with a delicate and rich vanilla cream and raspberry insert',
    nutrition: {
      fattyCalories: '17.92g',
      saturatedFatAcids: '10.08g',
      carbohydrates: '8.77g',
      sugars: '16g',
      proteins: '2.32g',
      salts: '0.04g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood5',
    type: 'pastryGood',
    price: '1.50$',
    name: 'Mini Babka',
    img: 'pictures/pastryGood5.jpg',
    description:
      'The balanced taste between the crunchy butter, the nutty chocolate cream and the rich flavor of the fruit shit creates a symphony of flavors that delights the senses',
    nutrition: {
      fattyCalories: '86.26g',
      saturatedFatAcids: '7.89g',
      carbohydrates: '0.91g',
      sugars: '5.59g',
      proteins: '6.56g',
      salts: '0.51g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood6',
    type: 'pastryGood',
    price: '2.30$',
    name: 'Cookie Caramel NY Good',
    img: 'pictures/pastryGood6.jpg',
    description:
      'A puff pastry with a crunchy texture provided by the cookie with chocolate drinks and salted caramel insert',
    nutrition: {
      fattyCalories: '4.14g',
      saturatedFatAcids: '2.67g',
      carbohydrates: '17.31g',
      sugars: '13.07g',
      proteins: '0.39g',
      salts: '0.01g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood7',
    price: '2.30$',
    name: 'New York Rolls',
    img: 'pictures/pastryGood7.jpg',
    description:
      'New York Rolls are a true phenomenon in the global dessert industry, conquering online and offline in a few months and gathering endless queues at the door of confectionery',
    nutrition: {
      fattyCalories: '31.89g',
      saturatedFatAcids: '22.62g',
      carbohydrates: '32.50g',
      sugars: '15.79g',
      proteins: '6.11g',
      salts: '0.52g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Pistachio', 'Soy'],
  },
  {
    id: 'pastryGood8',
    price: '2.30$',
    name: 'Dubai to NY Good',
    img: 'pictures/pastryGood8.jpg',
    description:
      'Crisp puff pastry, filled with kataif and pistachio cream, perfected with chocolate ganache... an explosion of flavors that conquers you instantly',
    nutrition: {
      fattyCalories: '4.14g',
      saturatedFatAcids: '2.67g',
      carbohydrates: '17.31g',
      sugars: '13.07g',
      proteins: '0.39g',
      salts: '0.01g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
];

export const tarts = [
  {
    id: 'tart1',
    type: 'tart',
    price: '10$',
    name: 'Coffee & Black Sesame Tart',
    img: 'pictures/tart1.jpg',
    description:
      'A combination of special flavors, which you will love from the moment you see it. Coffee blends wonderfully with the taste of almonds and caramel, creating a tart full of delights',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart2',
    type: 'tart',
    price: '10$',
    name: 'Blackberry & Black Chocolate',
    img: 'pictures/tart2.jpg',
    description:
      'A refined dessert, perfect for lovers of intense tastes. The special aromas of almonds and chocolate come over the tender dough',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart3',
    type: 'tart',
    price: '10$',
    name: 'Exotic Tart',
    img: 'pictures/tart3.jpg',
    description:
      'A tart with an exotic and colorful taste, a story in which fruity flavors create surprise after surprise, all extraordinarily delicious',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart4',
    type: 'tart',
    price: '10$',
    name: 'Strawberry & White Chocolate',
    img: 'pictures/tart4.jpg',
    description:
      'The combination of white chocolate and strawberries is irresistible, and this tart perfectly combines the sweetness of chocolate with the fresh aroma of fruit',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart5',
    type: 'tart',
    price: '10$',
    name: 'Lemon Meringue',
    img: 'pictures/tart5.jpg',
    description:
      'The lemon and meringue tart is a fine and refreshing dessert, a perfectly balanced combination between the sour taste of the lemon and the sweetness of the meringue',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart6',
    type: 'tart',
    price: '10$',
    name: 'All Nuts',
    img: 'pictures/tart6.jpg',
    description:
      'This tart is an irresistible dessert, full of flavor. The chocolate and sweet praline placed on the crispy dough harmonize perfectly with the caramelized nuts, creating a special treat',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart7',
    type: 'tart',
    price: '10$',
    name: 'Matcha Raspberry',
    img: 'pictures/tart7.jpg',
    description:
      'This tart is a light and surprising combination of tastes, refreshing and smooth. It conquers you from the first spoonful with the perfect harmony',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
];

export const plates = [
  {
    id: 'plate1',
    type: 'plate',
    price: '5$',
    name: 'Mini Pavlova',
    img: 'pictures/plate1.jpg',
    description:
      'Pavlova is a spectacular cake both in terms of design and flavors',
    nutrition: {
      fattyCalories: '11.26g',
      saturatedFatAcids: '5.84g',
      carbohydrates: '7.53g',
      sugars: '14.25g',
      proteins: '4.54g',
      salts: '0.30g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'plate2',
    type: 'plate',
    price: '5$',
    name: 'Mini Tarts',
    img: 'pictures/plate2.jpg',
    description:
      'Tender dough with a slightly crispy shell and fine cream, all completed with a wonderful decoration of fruit, meringue or caramelized nuts',
    nutrition: {
      fattyCalories: '29.41g',
      saturatedFatAcids: '18.17g',
      carbohydrates: '34.95g',
      sugars: '15.94g',
      proteins: '5.31g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
  {
    id: 'plate3',
    type: 'plate',
    price: '5$',
    name: 'Mini Cannoli',
    img: 'pictures/plate3.jpg',
    description:
      'Mini cannoli packages bring you the ideal combination of soft and sweet dough and aromatic and refreshing ricotta cream for dessert',
    nutrition: {
      fattyCalories: '14.07g',
      saturatedFatAcids: '3.06g',
      carbohydrates: '21.42g',
      sugars: '21.59g',
      proteins: '5.92g',
      salts: '0.35g',
    },
    allergens: ['Eggs', 'Lupine', 'Mustard', 'Soy'],
  },
  {
    id: 'plate4',
    type: 'plate',
    price: '5$',
    name: 'Cake Pops',
    img: 'pictures/plate4.jpg',
    description:
      'Lollipops are some of the most popular event desserts. They are easy to eat, with the most delicious flavors and create a very pleasant visual effect',
    nutrition: {
      fattyCalories: '14.07g',
      saturatedFatAcids: '3.06g',
      carbohydrates: '21.42g',
      sugars: '21.59g',
      proteins: '5.92g',
      salts: '0.35g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
  {
    id: 'plate5',
    type: 'plate',
    price: '5$',
    name: 'Salted Caramel Cheesecake',
    img: 'pictures/plate5.jpg',
    description:
      'Delicate cheese, friendly crust and salted caramel topping. These mini cheesecakes create a spectacle of textures and tastes',
    nutrition: {
      fattyCalories: '22g',
      saturatedFatAcids: '13.65g',
      carbohydrates: '2.68g',
      sugars: '2.22g',
      proteins: '2.48g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'plate6',
    type: 'plate',
    price: '5$',
    name: 'Berry Cheesecake',
    img: 'pictures/plate6.jpg',
    description:
      "They are good-looking, attractive and, above all, delicious. Mini cheesecakes are the dessert you can't go wrong with",
    nutrition: {
      fattyCalories: '22g',
      saturatedFatAcids: '13.65g',
      carbohydrates: '2.68g',
      sugars: '2.22g',
      proteins: '2.48g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
];

export const productList = [
  {
    id: 'cake1',
    type: 'cake',
    category: 'Cakes',
    price: '35',
    name: 'Rose Red Velvet Cake',
    img: '/pictures/cake1.jpg',
    description: 'The fluffy top and the graceful cream create a fabulous cake',
    nutrition: {
      fattyCalories: '80.15g',
      saturatedFatAcids: '10.65g',
      carbohydrates: '1.74g',
      sugars: '1.88g',
      proteins: '2.43g',
      salts: '0.22g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs'],
  },
  {
    id: 'cake2',
    type: 'cake',
    category: 'Cakes',
    price: '45',
    name: 'Praline Choco Cake',
    img: '/pictures/cake2.jpg',
    description:
      'Praline Choco Cake is a delicious mix of crunchy and fine textures and dense flavors',
    nutrition: {
      fattyCalories: '32.53g',
      saturatedFatAcids: '15.48g',
      carbohydrates: '13.12g',
      sugars: '21.67g',
      proteins: '4.76g',
      salts: '0.14g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs', 'Soy'],
  },
  {
    id: 'cake3',
    type: 'cake',
    category: 'Cakes',
    price: '40',
    name: 'Berry Choco Cake',
    img: '/pictures/cake3.jpg',
    description:
      'The Berry Choco cake comes with aromatic but perfectly balanced surprises',
    nutrition: {
      fattyCalories: '58.88g',
      saturatedFatAcids: '11.91g',
      carbohydrates: '8.72g',
      sugars: '13.93g',
      proteins: '2.77g',
      salts: '0.18g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs'],
  },
  {
    id: 'cake4',
    type: 'cake',
    category: 'Cakes',
    price: '40',
    name: 'Cherry Vanilla Cake',
    img: '/pictures/cake4.jpg',
    description:
      'Cherry Vanilla is a classic cake, a perfect combination between the delicate aroma of vanilla and the sweet-sour taste of cherries',
    nutrition: {
      fattyCalories: '10.92g',
      saturatedFatAcids: '12.43g',
      carbohydrates: '27.92g',
      sugars: '15.05g',
      proteins: '4.15g',
      salts: '0.78g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs'],
  },
  {
    id: 'cake5',
    type: 'cake',
    category: 'Cakes',
    price: '40',
    name: 'Cherry Choco Cake',
    img: '/pictures/cake5.jpg',
    description:
      'A tasty chocolate treat in which cherries come to balance the strong taste and give it a refresh',
    nutrition: {
      fattyCalories: '45.68g',
      saturatedFatAcids: '10.84g',
      carbohydrates: '35g',
      sugars: '30.31g',
      proteins: '3.08g',
      salts: '0.64g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs', 'Soy'],
  },
  {
    id: 'cake6',
    type: 'cake',
    category: 'Cakes',
    price: '40',
    name: 'Black Orange Cake',
    img: '/pictures/cake6.jpg',
    description:
      'The Black Orange cake is the embodiment of perfection. Dark chocolate blends wonderfully with the aroma of juicy and tasty oranges',
    nutrition: {
      fattyCalories: '23.12g',
      saturatedFatAcids: '11.44g',
      carbohydrates: '16g',
      sugars: '21.33g',
      proteins: '4.93g',
      salts: '0.12g',
    },
    allergens: ['Milk', 'Gluten', 'Eggs', 'Soy'],
  },
  {
    id: 'cookie1',
    type: 'cookie',
    category: 'Cookies',
    price: '4',
    name: 'Minidrip',
    img: '/pictures/cookie1.jpg',
    description:
      'Cake with cocoa top, Belgian white chocolate mousse with mixed berries',
    nutrition: {
      fattyCalories: '15.96g',
      saturatedFatAcids: '8.22g',
      carbohydrates: '28.63g',
      sugars: '22.41g',
      proteins: '5.37g',
      salts: '0.14g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'cookie2',
    type: 'cookie',
    category: 'Cookies',
    price: '3',
    name: 'Ispahan',
    img: '/pictures/cookie2.jpg',
    description:
      'Macarons with rose cream, white chocolate ganache, lychee and raspberry',
    nutrition: {
      fattyCalories: '27.72g',
      saturatedFatAcids: '19.82g',
      carbohydrates: '22.51g',
      sugars: '20.73g',
      proteins: '3.87g',
      salts: '0.19g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'cookie3',
    type: 'cookie',
    category: 'Cookies',
    price: '3',
    name: 'Amandine',
    img: '/pictures/cookie3.jpg',
    description: 'Cocoa cake, gold chocolate syrup, rum and cocoa cream',
    nutrition: {
      fattyCalories: '23.58g',
      saturatedFatAcids: '15.82g',
      carbohydrates: '36.28g',
      sugars: '31.09g',
      proteins: '4.63g',
      salts: '0.16g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'cookie4',
    type: 'cookie',
    category: 'Cookies',
    price: '2.80',
    name: 'Pistachio tart',
    img: '/pictures/cookie4.jpg',
    description:
      'Tart with pistachio cream, ganache and crunchy pistachio praline',
    nutrition: {
      fattyCalories: '27.72g',
      saturatedFatAcids: '19.82g',
      carbohydrates: '22.51g',
      sugars: '20.73g',
      proteins: '3.87g',
      salts: '0.19g',
    },
    allergens: [
      'Eggs',
      'Wheat Flour',
      'Milk and derived products',
      'Pistachio',
    ],
  },
  {
    id: 'cookie5',
    type: 'cookie',
    category: 'Cookies',
    price: '2.80',
    name: 'Pavlova',
    img: '/pictures/cookie5.jpg',
    description:
      'Meringue with mascarpone cream, strawberry jelly and red fruits',
    nutrition: {
      fattyCalories: '9.98g',
      saturatedFatAcids: '2.13g',
      carbohydrates: '28.48g',
      sugars: '19.06g',
      proteins: '4.28g',
      salts: '0.10g',
    },
    allergens: ['Eggs', 'Milk and derived products'],
  },
  {
    id: 'cookie6',
    type: 'cookie',
    category: 'Cookies',
    price: '4',
    name: 'Melia',
    img: '/pictures/cookie6.jpg',
    description:
      'Almond crust with a crunchy layer of feuilletine and chocolate, passion fruit mousse and cremeaux and orange confit insert',
    nutrition: {
      fattyCalories: '17.21g',
      saturatedFatAcids: '8.76g',
      carbohydrates: '32.25g',
      sugars: '24.37g',
      proteins: '5.21g',
      salts: '0.17g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron1',
    type: 'macaron',
    category: 'Macarons',
    price: '1',
    name: 'Vanilla macaron',
    img: '/pictures/macaron1.jpg',
    description: 'Macarons with vanilla cream',
    nutrition: {
      fattyCalories: '20.71g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '46.76g',
      sugars: '25.41g',
      proteins: '6.47g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron2',
    type: 'macaron',
    category: 'Macarons',
    price: '1',
    name: 'Chocolate macaron',
    img: '/pictures/macaron2.jpg',
    description: 'Macarons with chocolate cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron3',
    type: 'macaron',
    category: 'Macarons',
    price: '1',
    name: 'Macaron gianduja',
    img: '/pictures/macaron3.jpg',
    description: 'Macarons with gianduja cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: [
      'Eggs',
      'Milk and derived products',
      'Almond',
      'Forest Hazelnuts',
    ],
  },
  {
    id: 'macaron4',
    type: 'macaron',
    category: 'Macarons',
    price: '1',
    name: 'Caramel macaron',
    img: '/pictures/macaron4.jpg',
    description: 'Macarons with caramel cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron5',
    type: 'macaron',
    category: 'Macarons',
    price: '1',
    name: 'Macaron with chocolate cream and bananas',
    img: '/pictures/macaron5.jpg',
    description: 'Macarons with banana cream',
    nutrition: {
      fattyCalories: '20.82g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '47.53g',
      sugars: '26.24g',
      proteins: '6.53g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'macaron6',
    type: 'macaron',
    category: 'Macarons',
    price: '1',
    name: 'Coconut macaron with raspberry',
    img: '/pictures/macaron6.jpg',
    description: 'Macarons with coconut cream and raspberry confit',
    nutrition: {
      fattyCalories: '20.71g',
      saturatedFatAcids: '7.71g',
      carbohydrates: '46.76g',
      sugars: '25.41g',
      proteins: '6.47g',
      salts: '0.12g',
    },
    allergens: ['Eggs', 'Milk and derived products', 'Almond'],
  },
  {
    id: 'eclair1',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Raspberry Blush Eclair',
    img: '/pictures/eclair1.jpg',
    description: 'Eclair with raspberry cream',
    nutrition: {
      fattyCalories: '19.84g',
      saturatedFatAcids: '12.15g',
      carbohydrates: '20.57g',
      sugars: '14g',
      proteins: '6.34g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair2',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Vanilla Cream Eclair',
    img: '/pictures/eclair2.jpg',
    description: 'Eclair with vanilla cream',
    nutrition: {
      fattyCalories: '22.04g',
      saturatedFatAcids: '11.10g',
      carbohydrates: '16.63g',
      sugars: '10.22g',
      proteins: '5.68g',
      salts: '0.22g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair3',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Chocolate Mood Eclair',
    img: '/pictures/eclair3.jpg',
    description: 'Eclair with chocolate cream',
    nutrition: {
      fattyCalories: '22.84g',
      saturatedFatAcids: '13.54g',
      carbohydrates: '17.10g',
      sugars: '14.92g',
      proteins: '5.37g',
      salts: '0.18g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair4',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Mango Wish Eclair',
    img: '/pictures/eclair4.jpg',
    description: 'Eclair with mango cream',
    nutrition: {
      fattyCalories: '17.67g',
      saturatedFatAcids: '10.74g',
      carbohydrates: '22.46g',
      sugars: '12.75g',
      proteins: '5.74g',
      salts: '0.21g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair5',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Salty Caramel Eclair',
    img: '/pictures/eclair5.jpg',
    description: 'Eclair with salted caramel cream',
    nutrition: {
      fattyCalories: '28.59g',
      saturatedFatAcids: '16.69g',
      carbohydrates: '21.71g',
      sugars: '16.13g',
      proteins: '4.38g',
      salts: '0.50g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair6',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Coffee Cream Eclair',
    img: '/pictures/eclair6.jpg',
    description: 'Eclair with coffee cream',
    nutrition: {
      fattyCalories: '18.65g',
      saturatedFatAcids: '8.73g',
      carbohydrates: '16.96g',
      sugars: '9.14g',
      proteins: '4.82g',
      salts: '0.19g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair7',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Caramel Cream Eclair',
    img: '/pictures/eclair7.jpg',
    description: 'Eclair with sweet caramel cream and smooth milk chocolate',
    nutrition: {
      fattyCalories: '25.18g',
      saturatedFatAcids: '15.15g',
      carbohydrates: '33.16g',
      sugars: '25.50g',
      proteins: '5.76g',
      salts: '0.28g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'eclair8',
    type: 'eclair',
    category: 'Eclairs',
    price: '2.50',
    name: 'Coconut Dream Eclair',
    img: '/pictures/eclair8.jpg',
    description: 'Eclair with coconut cream',
    nutrition: {
      fattyCalories: '22.21g',
      saturatedFatAcids: '11.61g',
      carbohydrates: '30.28g',
      sugars: '21.22g',
      proteins: '5.84g',
      salts: '0.23g',
    },
    allergens: ['Eggs', 'Wheat Flour', 'Milk and derived products'],
  },
  {
    id: 'pastryGood1',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '1',
    name: 'Croissant',
    img: '/pictures/pastryGood1.jpg',
    description:
      'Every bite is a refined experience because our croissant is generous.',
    nutrition: {
      fattyCalories: '21g',
      saturatedFatAcids: '12g',
      carbohydrates: '46g',
      sugars: '11g',
      proteins: '8g',
      salts: '0.20g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
  {
    id: 'pastryGood2',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '2',
    name: 'Praline Croissant',
    img: '/pictures/pastryGood2.jpg',
    description:
      'Every bite is an explosion of taste thanks to our hazelnut cream, made from fresh and genuine hazelnuts',
    nutrition: {
      fattyCalories: '17.92g',
      saturatedFatAcids: '10.08g',
      carbohydrates: '8.77g',
      sugars: '16g',
      proteins: '2.32g',
      salts: '0.04g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood3',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '2',
    name: 'Salted Caramel Vanilla Croissant',
    img: '/pictures/pastryGood3.jpg',
    description:
      'Every bite is a refined experience, as our croissant is generously filled with a delicate and rich vanilla cream and salted caramel insert',
    nutrition: {
      fattyCalories: '17.92g',
      saturatedFatAcids: '10.08g',
      carbohydrates: '8.77g',
      sugars: '16g',
      proteins: '2.32g',
      salts: '0.04g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood4',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '2',
    name: 'Raspberry Vanilla Croissant',
    img: '/pictures/pastryGood4.jpg',
    description:
      'Every bite is a refined experience, as our croissant is generously filled with a delicate and rich vanilla cream and raspberry insert',
    nutrition: {
      fattyCalories: '17.92g',
      saturatedFatAcids: '10.08g',
      carbohydrates: '8.77g',
      sugars: '16g',
      proteins: '2.32g',
      salts: '0.04g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood5',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '1.50',
    name: 'Mini Babka',
    img: '/pictures/pastryGood5.jpg',
    description:
      'The balanced taste between the crunchy butter, the nutty chocolate cream and the rich flavor of the fruit shit creates a symphony of flavors that delights the senses',
    nutrition: {
      fattyCalories: '86.26g',
      saturatedFatAcids: '7.89g',
      carbohydrates: '0.91g',
      sugars: '5.59g',
      proteins: '6.56g',
      salts: '0.51g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood6',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '2.30',
    name: 'Cookie Caramel NY Good',
    img: '/pictures/pastryGood6.jpg',
    description:
      'A puff pastry with a crunchy texture provided by the cookie with chocolate drinks and salted caramel insert',
    nutrition: {
      fattyCalories: '4.14g',
      saturatedFatAcids: '2.67g',
      carbohydrates: '17.31g',
      sugars: '13.07g',
      proteins: '0.39g',
      salts: '0.01g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'pastryGood7',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '2.30',
    name: 'New York Rolls',
    img: '/pictures/pastryGood7.jpg',
    description:
      'New York Rolls are a true phenomenon in the global dessert industry, conquering online and offline in a few months and gathering endless queues at the door of confectionery',
    nutrition: {
      fattyCalories: '31.89g',
      saturatedFatAcids: '22.62g',
      carbohydrates: '32.50g',
      sugars: '15.79g',
      proteins: '6.11g',
      salts: '0.52g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Pistachio', 'Soy'],
  },
  {
    id: 'pastryGood8',
    type: 'pastryGood',
    category: 'Pastry Goods',
    price: '2.30',
    name: 'Dubai to NY Good',
    img: '/pictures/pastryGood8.jpg',
    description:
      'Crisp puff pastry, filled with kataif and pistachio cream, perfected with chocolate ganache... an explosion of flavors that conquers you instantly',
    nutrition: {
      fattyCalories: '4.14g',
      saturatedFatAcids: '2.67g',
      carbohydrates: '17.31g',
      sugars: '13.07g',
      proteins: '0.39g',
      salts: '0.01g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Sesame Seeds'],
  },
  {
    id: 'tart1',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'Coffee & Black Sesame Tart',
    img: '/pictures/tart1.jpg',
    description:
      'A combination of special flavors, which you will love from the moment you see it. Coffee blends wonderfully with the taste of almonds and caramel, creating a tart full of delights',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart2',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'Blackberry & Black Chocolate Tart',
    img: '/pictures/tart2.jpg',
    description:
      'A refined dessert, perfect for lovers of intense tastes. The special aromas of almonds and chocolate come over the tender dough',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart3',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'Exotic Tart',
    img: '/pictures/tart3.jpg',
    description:
      'A tart with an exotic and colorful taste, a story in which fruity flavors create surprise after surprise, all extraordinarily delicious',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart4',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'Strawberry & White Chocolate Tart',
    img: '/pictures/tart4.jpg',
    description:
      'The combination of white chocolate and strawberries is irresistible, and this tart perfectly combines the sweetness of chocolate with the fresh aroma of fruit',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart5',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'Lemon Meringue Tart',
    img: '/pictures/tart5.jpg',
    description:
      'The lemon and meringue tart is a fine and refreshing dessert, a perfectly balanced combination between the sour taste of the lemon and the sweetness of the meringue',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart6',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'All Nuts Tart',
    img: '/pictures/tart6.jpg',
    description:
      'This tart is an irresistible dessert, full of flavor. The chocolate and sweet praline placed on the crispy dough harmonize perfectly with the caramelized nuts, creating a special treat',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'tart7',
    type: 'tart',
    category: 'Tarts',
    price: '10',
    name: 'Matcha Raspberry Tart',
    img: '/pictures/tart7.jpg',
    description:
      'This tart is a light and surprising combination of tastes, refreshing and smooth. It conquers you from the first spoonful with the perfect harmony',
    nutrition: {
      fattyCalories: '13.39g',
      saturatedFatAcids: '7.13g',
      carbohydrates: '40.06g',
      sugars: '16.27g',
      proteins: '4.78g',
      salts: '0.08g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'plate1',
    type: 'plate',
    category: 'Mini Sweet Plates',
    price: '5',
    name: 'Mini Pavlova',
    img: '/pictures/plate1.jpg',
    description:
      'Pavlova is a spectacular cake both in terms of design and flavors',
    nutrition: {
      fattyCalories: '11.26g',
      saturatedFatAcids: '5.84g',
      carbohydrates: '7.53g',
      sugars: '14.25g',
      proteins: '4.54g',
      salts: '0.30g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'plate2',
    type: 'plate',
    category: 'Mini Sweet Plates',
    price: '5',
    name: 'Mini Tarts',
    img: '/pictures/plate2.jpg',
    description:
      'Tender dough with a slightly crispy shell and fine cream, all completed with a wonderful decoration of fruit, meringue or caramelized nuts',
    nutrition: {
      fattyCalories: '29.41g',
      saturatedFatAcids: '18.17g',
      carbohydrates: '34.95g',
      sugars: '15.94g',
      proteins: '5.31g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
  {
    id: 'plate3',
    type: 'plate',
    category: 'Mini Sweet Plates',
    price: '5',
    name: 'Mini Cannoli',
    img: '/pictures/plate3.jpg',
    description:
      'Mini cannoli packages bring you the ideal combination of soft and sweet dough and aromatic and refreshing ricotta cream for dessert',
    nutrition: {
      fattyCalories: '14.07g',
      saturatedFatAcids: '3.06g',
      carbohydrates: '21.42g',
      sugars: '21.59g',
      proteins: '5.92g',
      salts: '0.35g',
    },
    allergens: ['Eggs', 'Lupine', 'Mustard', 'Soy'],
  },
  {
    id: 'plate4',
    type: 'plate',
    category: 'Mini Sweet Plates',
    price: '5',
    name: 'Cake Pops',
    img: '/pictures/plate4.jpg',
    description:
      'Lollipops are some of the most popular event desserts. They are easy to eat, with the most delicious flavors and create a very pleasant visual effect',
    nutrition: {
      fattyCalories: '14.07g',
      saturatedFatAcids: '3.06g',
      carbohydrates: '21.42g',
      sugars: '21.59g',
      proteins: '5.92g',
      salts: '0.35g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
  {
    id: 'plate5',
    type: 'plate',
    category: 'Mini Sweet Plates',
    price: '5',
    name: 'Salted Caramel Cheesecake',
    img: '/pictures/plate5.jpg',
    description:
      'Delicate cheese, friendly crust and salted caramel topping. These mini cheesecakes create a spectacle of textures and tastes',
    nutrition: {
      fattyCalories: '22g',
      saturatedFatAcids: '13.65g',
      carbohydrates: '2.68g',
      sugars: '2.22g',
      proteins: '2.48g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten', 'Soy'],
  },
  {
    id: 'plate6',
    type: 'plate',
    category: 'Mini Sweet Plates',
    price: '5',
    name: 'Berry Cheesecake',
    img: '/pictures/plate6.jpg',
    description:
      "They are good-looking, attractive and, above all, delicious. Mini cheesecakes are the dessert you can't go wrong with",
    nutrition: {
      fattyCalories: '22g',
      saturatedFatAcids: '13.65g',
      carbohydrates: '2.68g',
      sugars: '2.22g',
      proteins: '2.48g',
      salts: '0.24g',
    },
    allergens: ['Eggs', 'Milk', 'Gluten'],
  },
];
